name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Android Kernel Build Action
        uses: dabao1955/kernel_build_action@v1.10.0
        with:
          kernel-url: https://github.com/GanPengZx/android_kernel_oppo_sm6375
          kernel-branch: oppo/sm6375_t_13.1.0_oppo_a1_5g
          config: phs110_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r383902
